name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python for Pages
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies (if needed)
      run: |
        pip install -r requirements.txt  # If you need any dependencies

    - name: Build the website
      run: |
        # If you need to build something (e.g., SASS, JavaScript bundling)
        # run your build commands here, e.g., npm install && npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Publish the root directory
        branch: main  # Deploy to the 'gh-pages' branch
